query postListQuery {
  postConnection {
    edges {
      node {
        id
        title
        category
        publishedAt
        readTime
        description
        _sys {
          filename
        }
      }
    }
  }
}

query postQuery($relativePath: String!) {
  post(relativePath: $relativePath) {
    ...PostParts
  }
}

query categoryListQuery {
  categoryConnection {
    edges {
      node {
        id
        name
        description
        _sys {
          filename
        }
      }
    }
  }
}
